using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DomainSchema.Generator;

[Generator]
public sealed class DomainSchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var yamlFiles = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".yaml", StringComparison.OrdinalIgnoreCase));

        var models = yamlFiles.Select(static (file, ct) =>
            SchemaParser.Parse(file.GetText(ct)?.ToString() ?? string.Empty));

        context.RegisterSourceOutput(models, static (spc, model) =>
        {
            if (model is null) return;
            spc.AddSource($"{model.Name}Immutable.g.cs", EmitImmutable(model));
            spc.AddSource($"{model.Name}Builder.g.cs", EmitBuilder(model));
            spc.AddSource($"{model.Name}Mutable.g.cs", EmitMutable(model));
            spc.AddSource($"{model.Name}Projection.g.cs", EmitProjection(model));
        });
    }

    static string ToCsharpType(string kind) => kind switch
    {
        "guid"    => "Guid",
        "int"     => "int",
        "decimal" => "decimal",
        "bool"    => "bool",
        _         => "string"
    };

    static string DefaultValue(string kind) => kind switch
    {
        "guid"    => "default",
        "int"     => "0",
        "decimal" => "0m",
        "bool"    => "false",
        _         => "\"\""
    };

    static string RelType(DomainRelationship r) =>
        r.Cardinality == "many"
            ? $"IReadOnlyList<{r.Target}Immutable>"
            : $"{r.Target}Immutable?";

    static string Lower(string s) =>
        s.Length == 0 ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);

    static string EmitImmutable(DomainType m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace DomainSchema.Generated;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using DomainModel.Runtime;");
        sb.AppendLine();

        var ps = new List<string>();
        foreach (var f in m.Fields) ps.Add($"{ToCsharpType(f.Kind)} {f.Name}");
        foreach (var r in m.Relationships) ps.Add($"{RelType(r)} {r.Name}");

        sb.AppendLine($"public sealed record {m.Name}Immutable({string.Join(", ", ps)})");
        sb.AppendLine("{");

        // ToMutable
        sb.AppendLine($"    public {m.Name}Mutable ToMutable()");
        sb.AppendLine("    {");
        sb.AppendLine($"        var mut = new {m.Name}Mutable();");
        foreach (var f in m.Fields) sb.AppendLine($"        mut.{f.Name} = {f.Name};");
        foreach (var r in m.Relationships) sb.AppendLine($"        mut.{r.Name} = {r.Name};");
        sb.AppendLine("        mut.AcceptChanges();");
        sb.AppendLine("        return mut;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ToProjection
        var projArgs = new List<string>();
        foreach (var f in m.Fields)
            if (!f.ExcludeFromProjection) projArgs.Add(f.Name);
        sb.AppendLine($"    public {m.Name}Projection ToProjection() =>");
        sb.AppendLine($"        new {m.Name}Projection({string.Join(", ", projArgs)});");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string EmitBuilder(DomainType m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace DomainSchema.Generated;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {m.Name}Builder");
        sb.AppendLine("{");

        foreach (var f in m.Fields)
            sb.AppendLine($"    private {ToCsharpType(f.Kind)} _{Lower(f.Name)} = {DefaultValue(f.Kind)};");
        foreach (var r in m.Relationships)
            sb.AppendLine($"    private {RelType(r)} _{Lower(r.Name)};");
        sb.AppendLine();

        foreach (var f in m.Fields)
            sb.AppendLine($"    public {m.Name}Builder With{f.Name}({ToCsharpType(f.Kind)} value) {{ _{Lower(f.Name)} = value; return this; }}");
        foreach (var r in m.Relationships)
            sb.AppendLine($"    public {m.Name}Builder With{r.Name}({RelType(r)} value) {{ _{Lower(r.Name)} = value; return this; }}");
        sb.AppendLine();

        // Validate constraints, then build
        bool hasConstraints = false;
        foreach (var f in m.Fields) if (f.Constraint != null) { hasConstraints = true; break; }

        sb.AppendLine($"    public {m.Name}Immutable Build()");
        sb.AppendLine("    {");
        if (hasConstraints)
        {
            foreach (var f in m.Fields)
            {
                if (f.Constraint == null) continue;
                if (f.Constraint.Kind == "non_empty")
                    sb.AppendLine($"        if (string.IsNullOrEmpty(_{Lower(f.Name)})) throw new ArgumentException(\"{f.Name} must not be empty.\", \"{f.Name}\");");
                else if (f.Constraint.Kind == "range")
                    sb.AppendLine($"        if (_{Lower(f.Name)} < {f.Constraint.RangeMin} || _{Lower(f.Name)} > {f.Constraint.RangeMax}) throw new ArgumentOutOfRangeException(\"{f.Name}\", \"{f.Name} must be between {f.Constraint.RangeMin} and {f.Constraint.RangeMax}.\");");
            }
        }
        var ctorArgs = new List<string>();
        foreach (var f in m.Fields) ctorArgs.Add($"_{Lower(f.Name)}");
        foreach (var r in m.Relationships) ctorArgs.Add($"_{Lower(r.Name)}");
        sb.AppendLine($"        return new {m.Name}Immutable({string.Join(", ", ctorArgs)});");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string EmitMutable(DomainType m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace DomainSchema.Generated;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using DomainModel.Runtime;");
        sb.AppendLine();

        sb.AppendLine($"public sealed class {m.Name}Mutable : IChangeTracking");
        sb.AppendLine("{");
        sb.AppendLine("    private ChangeSet _changes;");
        sb.AppendLine();

        // Backing fields + ordered member list for bit indices
        var members = new List<(string Name, string Type)>();
        foreach (var f in m.Fields)
        {
            sb.AppendLine($"    private {ToCsharpType(f.Kind)} _{Lower(f.Name)} = {DefaultValue(f.Kind)};");
            members.Add((f.Name, ToCsharpType(f.Kind)));
        }
        foreach (var r in m.Relationships)
        {
            sb.AppendLine($"    private {RelType(r)} _{Lower(r.Name)};");
            members.Add((r.Name, RelType(r)));
        }
        sb.AppendLine();

        // Change-tracked properties
        for (int i = 0; i < members.Count; i++)
        {
            var (name, type) = members[i];
            sb.AppendLine($"    public {type} {name}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => _{Lower(name)};");
            sb.AppendLine($"        set {{ _{Lower(name)} = value; _changes.Set({i}); }}");
            sb.AppendLine("    }");
        }
        sb.AppendLine();

        // IChangeTracking
        sb.AppendLine("    public bool HasChanges => _changes.Any;");
        sb.AppendLine();
        sb.AppendLine("    public IReadOnlyList<string> ChangedFields");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine("            var result = new List<string>();");
        for (int i = 0; i < members.Count; i++)
            sb.AppendLine($"            if (_changes.IsSet({i})) result.Add(\"{members[i].Name}\");");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void AcceptChanges() => _changes.Clear();");
        sb.AppendLine();

        // ToImmutable
        var immArgs = new List<string>();
        foreach (var f in m.Fields) immArgs.Add(f.Name);
        foreach (var r in m.Relationships) immArgs.Add(r.Name);
        sb.AppendLine($"    public {m.Name}Immutable ToImmutable() => new {m.Name}Immutable({string.Join(", ", immArgs)});");
        sb.AppendLine();

        // ToProjection
        var projArgs = new List<string>();
        foreach (var f in m.Fields)
            if (!f.ExcludeFromProjection) projArgs.Add(f.Name);
        sb.AppendLine($"    public {m.Name}Projection ToProjection() => new {m.Name}Projection({string.Join(", ", projArgs)});");
        sb.AppendLine();

        // Structural equality
        sb.AppendLine("    public override bool Equals(object? obj)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (obj is not {m.Name}Mutable other) return false;");
        var eqParts = new List<string>();
        foreach (var (name, _) in members) eqParts.Add($"{name} == other.{name}");
        sb.AppendLine($"        return {string.Join(" && ", eqParts)};");
        sb.AppendLine("    }");
        sb.AppendLine();

        // GetHashCode
        var allNames = new List<string>();
        foreach (var (name, _) in members) allNames.Add(name);
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");
        if (allNames.Count <= 8)
        {
            sb.AppendLine($"        return HashCode.Combine({string.Join(", ", allNames)});");
        }
        else
        {
            sb.AppendLine("        var hash = new HashCode();");
            foreach (var n in allNames) sb.AppendLine($"        hash.Add({n});");
            sb.AppendLine("        return hash.ToHashCode();");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static string EmitProjection(DomainType m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace DomainSchema.Generated;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        var ps = new List<string>();
        foreach (var f in m.Fields)
            if (!f.ExcludeFromProjection) ps.Add($"{ToCsharpType(f.Kind)} {f.Name}");
        sb.AppendLine($"public sealed record {m.Name}Projection({string.Join(", ", ps)});");
        return sb.ToString();
    }
}
