// <auto-generated/>
#nullable enable
namespace DomainSchema.Generated;

using System;
using System.Collections.Generic;
using DomainModel.Runtime;

public sealed class CustomerMutable : IChangeTracking
{
    private ChangeSet _changes;

    private Guid _id = default;
    private string _fullName = "";
    private string _email = "";
    private int _age = 0;
    private string _notes = "";
    private AddressImmutable? _address;

    public Guid Id
    {
        get => _id;
        set { _id = value; _changes.Set(0); }
    }
    public string FullName
    {
        get => _fullName;
        set { _fullName = value; _changes.Set(1); }
    }
    public string Email
    {
        get => _email;
        set { _email = value; _changes.Set(2); }
    }
    public int Age
    {
        get => _age;
        set { _age = value; _changes.Set(3); }
    }
    public string Notes
    {
        get => _notes;
        set { _notes = value; _changes.Set(4); }
    }
    public AddressImmutable? Address
    {
        get => _address;
        set { _address = value; _changes.Set(5); }
    }

    public bool HasChanges => _changes.Any;

    public IReadOnlyList<string> ChangedFields
    {
        get
        {
            var result = new List<string>();
            if (_changes.IsSet(0)) result.Add("Id");
            if (_changes.IsSet(1)) result.Add("FullName");
            if (_changes.IsSet(2)) result.Add("Email");
            if (_changes.IsSet(3)) result.Add("Age");
            if (_changes.IsSet(4)) result.Add("Notes");
            if (_changes.IsSet(5)) result.Add("Address");
            return result;
        }
    }

    public void AcceptChanges() => _changes.Clear();

    public CustomerImmutable ToImmutable() => new CustomerImmutable(Id, FullName, Email, Age, Notes, Address);

    public CustomerProjection ToProjection() => new CustomerProjection(Id, FullName, Email, Age);

    public override bool Equals(object? obj)
    {
        if (obj is not CustomerMutable other) return false;
        return Id == other.Id && FullName == other.FullName && Email == other.Email && Age == other.Age && Notes == other.Notes && Address == other.Address;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(Id, FullName, Email, Age, Notes, Address);
    }
}
