// <auto-generated/>
#nullable enable
namespace DomainSchema.Generated;

using System;
using System.Collections.Generic;

public sealed class CustomerBuilder
{
    private Guid _id = default;
    private string _fullName = "";
    private string _email = "";
    private int _age = 0;
    private string _notes = "";
    private AddressImmutable? _address;

    public CustomerBuilder WithId(Guid value) { _id = value; return this; }
    public CustomerBuilder WithFullName(string value) { _fullName = value; return this; }
    public CustomerBuilder WithEmail(string value) { _email = value; return this; }
    public CustomerBuilder WithAge(int value) { _age = value; return this; }
    public CustomerBuilder WithNotes(string value) { _notes = value; return this; }
    public CustomerBuilder WithAddress(AddressImmutable? value) { _address = value; return this; }

    public CustomerImmutable Build()
    {
        if (string.IsNullOrEmpty(_fullName)) throw new ArgumentException("FullName must not be empty.", "FullName");
        if (_age < 0 || _age > 150) throw new ArgumentOutOfRangeException("Age", "Age must be between 0 and 150.");
        return new CustomerImmutable(_id, _fullName, _email, _age, _notes, _address);
    }
}
