// <auto-generated/>
#nullable enable
namespace DomainSchema.Generated;

using System;
using System.Collections.Generic;
using DomainModel.Runtime;

public sealed record CustomerImmutable(Guid Id, string FullName, string Email, int Age, string Notes, AddressImmutable? Address)
{
    public CustomerMutable ToMutable()
    {
        var mut = new CustomerMutable();
        mut.Id = Id;
        mut.FullName = FullName;
        mut.Email = Email;
        mut.Age = Age;
        mut.Notes = Notes;
        mut.Address = Address;
        mut.AcceptChanges();
        return mut;
    }

    public CustomerProjection ToProjection() =>
        new CustomerProjection(Id, FullName, Email, Age);
}
